symbol_list = {
    'AAPL': ['Apple', 'Appl'],
    'AMC': ['AMC Entertainment Holdings', 'AAMC'],
    'AMZN': ['Amazon.com', 'Amazn', 'Amazon'],
    'AMD': ['Advanced Micro Devices', 'AMED'],
    'BB': ['Blacberry'],
    'BBBY': ['Bed Bath Beyond', 'Bedbathbeyond'],
    'BTC': ['Bitcoin', 'bit coin'],
    'BYND': ['Beyond Meat', 'Bynd'],
    'CLNE': ['Clean Energy Fuels', 'Clnenergy'],
    'CMG': ['Chipotle Mexican Grill', 'Chipotle'],
    'CRSR': ['Corsair Gaming', 'Corsair'],
    'DOGE': ['Dogecoin', 'Doge coin'],
    'ETH': ['Ethereum', 'Etherium'],
    'FB': ['Facebook', 'Fb'],
    'GME': ['Gamestop'],
    'GOOG': ['Alphabet', 'Google'],
    'HD': ['Home Depot', 'Home Depo'],
    'INTC': ['Intel', 'Intell'],
    'JNJ': ['Johnson Johnson', 'Johnsohn'],
    'LULU': ['Lululemon Athletica', 'Lululemn'],
    'MCD': ["McDonald's", "McDonalds"],
    'MGM': ['MGM Resorts International', 'Mgmresorts', 'Mgm resorts'],
    'MSFT': ['Microsoft', 'Micrsoft'],
    'NIO': ['NIO', 'Nio'],
    'NVDA': ['NVIDIA', 'Nivida'],
    'PFE': ['Pfizer', 'Pifzer'],
    'PINS': ['Pinterest', 'Pintrst'],
    'PLTR': ['Palantir Technologies', 'Palintir'],
    'QQQ': ['Invesco QQQ', 'InvescoQQQ'],
    'RBLX': ['Roblox', 'Robloks'],
    'ROKU': ['Roku', 'Rokue'],
    'SNDL': ['Sundial Growers', 'Sundail'],
    'SPCE': ['Virgin Galactic Holdings', 'Spacex'],
    'SQ': ['Square', 'Squar'],
    'TSLA': ['Tesla', 'Teslla'],
    'TWTR': ['Twitter', 'Twiter'],
    'UBER': ['Uber Technologies', 'Ube'],
    'UPST': ['Upstart Holdings', 'Upstartholdings'],
    'WMT': ['Walmart', 'Walmrt'],
    'XOM': ['Exxon Mobil', 'Exxonmobil'],
    'AAL': ['American Airlines Group', 'Americanairlines'],
    'ABNB': ['Airbnb', 'AirBnB'],
    'ACB': ['Aurora Cannabis', 'Auroracannabis'],
    'AMRN': ['Amarin', 'Amerin'],
    'ARKK': ['ARK Innovation', 'ARKinovation'],
    'BABA': ['Alibaba Group ', 'Alibaba'],
    'BAC': ['Bank of America', 'Bankofamerica'],
    'BIDU': ['Baidu', 'Bido'],
    'BILI': ['Bilibili', 'Billibili'],
    'BLNK': ['Blink Charging', 'Blinkcharg'],
    'BMY': ['Bristol Myers Squibb', 'Bristolmyers'],
    'BRK.A': ['Berkshire Hathaway', 'Berkshira'],
    'CCL': ['Carnival'],
    'CGC': ['Canopy Growth', 'Canopygrowth'],
    'CHWY': ['Chewy', 'Chewycom'],
    'CSCO': ['Cisco Systems', 'Cicsco'],
    'CVS': ['CVS Health', 'Cvshealth'],
    'DAL': ['Delta Air Lines', 'Deltaairlines'],
    'DDOG': ['Datadog', 'DataDog'],
    'DISCA': ['Discovery - Class A', 'Discovera'],
    'DKNG': ['DraftKings', 'DraftKings'],
    'ENPH': ['Enphase Energy', 'Enphase'],
    'EQT': ['EQT', 'Eqtcorporation'],
    'FCEL': ['FuelCell Energy', 'Fuelcell'],
    'FSLY': ['Fastly', 'Fastly'],
    'GOLD': ['Barrick Gold', 'Goldmining'],
    'GPRO': ['Gopro'],
    'GRWG': ['GrowGeneration', 'Growgen'],
    'HPE': ['Hewlett Packard Enterprise', 'Hewlettpackard'],
    'IBB': ['iShares NASDAQ Biotechnology', 'iSharesNasdaqBiotechnology'],
    'IBKR': ['Interactive Brokers Group', 'InterectiveBrokers'],
    'INO': ['Inovio Pharmaceuticals', 'Inovio'],
    'JD': ['JD.com', 'JD'],
    'JMIA': ['Jumia Technologies', 'Jumia'],
    'JPM': ['JPMorgan Chase', 'JPmorgan'],
    'KHC': ['Kraft Heinz', 'KraftHeinz'],
    'LIT': ['Global X Lithium & Battery Tech ETF', 'GlobalXlithium'],
    'MARA': ['Marathon Digital Holdings', 'MarathonDigital'],
    'MRNA': ['Moderna', 'Modernna'],
    'NCLH': ['Norwegian Cruise Line Holdings', 'Norwegiancruiseline'],
    'NET': ['Cloudflare', 'CloudFlare'],
    'NFLX': ['Netflix'],
    'NKE': ['Nike'],
    'NKLA': ['Nikola', 'Nicola'],
    'NOK': ['Nokia', 'Noka'],
    'OGI': ['OrganiGram Holdings', 'Organigram'],
    'OTRK': ['Ontrak', 'OnTrack'],
    'PDD': ['Pinduoduo', 'Pinduoduo'],
    'PENN': ['Penn National Gaming', 'PennNational'],
    'NQ': ['NASDAQ', 'Nasdaq'],
    'SPY': ['S&P 500 ETF Trust', 'SPDRS&P500', 'SPDR', 'SPY'],
    'ES-F': ['S&P 500 E-Mini Futures', 'S&P500E-Mini', 'S&P500E', 'S&P500', 'S&P'],
    'DJIA': ['Dow Jones Industrial Average', 'DowJones']
    }

adHoc_ignore = ['ET','COST', 'DIS', 'KO', 'BA', 'GE', 'LIT', 'PEN','GM',
                'BTC','ETH','LUNA','SOL','ATOM','ROSE','DOGE','ADA','XRP',
                'DOT','XLM','BCH','BNB','UNI','LINK','LTC','VET','ETC','EOS',
                'FIL','XMR','TRX','XTZ','NEO','ICP','CAKE','THETA','AAVE','ALGO',
                'MKR','BTT','AVAX','SUSHI','HNT','COMP','SNX','BAND','YFI','DASH','ZEC','RUNE']

ticker_list = ['AA', 'AAL', 'AAPL', 'ABNB', 'AEHR', 'AFRM', 'AMC', 'AMD', 'AMZN',
       'APE', 'AR', 'ARKK', 'ATOM', 'ATVI', 'BA', 'BABA', 'BAC', 'BB',
       'BBBY', 'BBY', 'BILI', 'BLK', 'BTU', 'C', 'CCJ', 'CCL', 'CF',
       'CLF', 'COIN', 'COST', 'CRM', 'CRWD', 'CS', 'CVNA', 'CVX', 'DAL',
       'DIA', 'DIS', 'DKNG', 'DWAC', 'ENPH', 'ES', 'ET', 'ETSY', 'F',
       'FDX', 'FSLR', 'GDX', 'GE', 'GME', 'GOLD', 'GOOG', 'GOOGL', 'GS',
       'HD', 'HOOD', 'IBM', 'INTC', 'ITUB', 'IWM', 'JNJ', 'JPM', 'KO',
       'LCID', 'LI', 'LINK', 'LIT', 'LMT', 'LTHM', 'LULU', 'LUNA', 'MARA',
       'MCD', 'META', 'MGM', 'MOS', 'MRNA', 'MS', 'MSFT', 'MU', 'NEAR',
       'NFLX', 'NIO', 'NKE', 'NVDA', 'OXY', 'PARA', 'PDD', 'PENN', 'PEP',
       'PFE', 'PLTR', 'PTON', 'PYPL', 'PYR', 'QCOM', 'QQQ', 'RBLX',
       'RDFN', 'RIVN', 'ROKU', 'SBUX', 'SE', 'SHOP', 'SLB', 'SMH', 'SNAP',
       'SNOW', 'SOFI', 'SOL', 'SPY', 'SQ', 'SQQQ', 'SWN', 'T', 'TGT',
       'TSLA', 'TSM', 'TWLO', 'TWTR', 'U', 'UAL', 'UBER', 'UNH', 'UPST',
       'UST', 'V', 'WFC', 'WMT', 'XBI', 'XLE', 'XOM', 'ZM']
